export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_DETAILS = "HANDLE_DETAILS";
export const HANDLE_COLOR = "HANDLE_COLOR";

export const HANDLE_WORK_EXPERIENCE = "HANDLE_WORK_EXPERIENCE";
export const ADD_WORK_EXPERIENCE = "ADD_WORK_EXPERIENCE";
export const REMOVE_WORK_EXPERIENCE = "REMOVE_WORK_EXPERIENCE";

export const HANDLE_ACADEMIC_HISTORY = "HANDLE_ACADEMIC_HISTORY";
export const ADD_ACADEMIC_HISTORY = "ADD_ACADEMIC_HISTORY";
export const REMOVE_ACADEMIC_HISTORY = "REMOVE_ACADEMIC_HISTORY";

export const HANDLE_DOWNLOAD = "HANDLE_DOWNLOAD";
