export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const RESET_DATA = "RESET_DATA";
export const HANDLE_COLOR = "HANDLE_COLOR";
export const DEMO_VALUE = "DEMO_VALUE";
export const HANDLE_TEMPLATE = "HANDLE_TEMPLATE";
export const HANDLE_FONTSIZE = "HANDLE_FONTSIZE";
export const HANDLE_TEMPLATE_SOURCECODE = "HANDLE_TEMPLATE_SOURCECODE";
